apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acs-central
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: petclinic
  target:
    name: acs-central
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ACS_SCAN_IMAGE
