apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: petclinic
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          tekton.dev/docker-0: https://quay.io
      data:
        .dockerconfigjson: "{{ .docker_secret | toString }}"
    name: docker-config
    creationPolicy: Owner
  data:
  - secretKey: docker_secret
    remoteRef:
      key: DOCKER_CONFIG_JSON
