apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: petclinic
spec:
  params:
    - name: SOURCE_GIT_REVISION
      type: string
      default: master
    - name: SOURCE_GIT_URL
      type: string
      default: https://github.com/gnunn-gitops/quarkus-petclinic
    - name: IMAGE_DEST_URL
      type: string
      description: External registry location to copy image to
      default: quay.io/gnunn/quarkus-petclinic
  tasks:
    - name: clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: URL
          value: "$(params.SOURCE_GIT_URL)"
        - name: REVISION
          value: "$(params.SOURCE_GIT_REVISION)"
        - name: DELETE_EXISTING
          value: "true"
    - name: generate-id
      taskRef:
        kind: Task
        params:
          - name: pathInRepo
            value: task/generate-build-id/1.0/generate-build-id.yaml
        resolver: git
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: git-source
    - name: compile
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - generate-id
      params:
        - name: GOALS
          value:
            - "package"
            - "-DskipTests"
    - name: build
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - compile
      params:
        - name: IMAGE
          value: $(params.IMAGE_DEST_URL):latest
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.hardened
        - name: BUILD_EXTRA_ARGS
          value: "--label=COMMIT=$(tasks.generate-id.results.short_commit) --label=BUILD_UID=$(tasks.generate-id.results.build_uid)"
    - name: tag-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - build
      params:
        - name: SRC_IMAGE
          value: $(params.IMAGE_DEST_URL)@$(tasks.build.results.IMAGE_DIGEST)
        - name: DEST_IMAGE
          value: $(params.IMAGE_DEST_URL)
        - name: DEST_TAGS
          value: "$(tasks.generate-id.results.tag_id)"
    - name: generate-sbom
      taskRef:
        kind: Task
        params:
          - name: pathInRepo
            value: task/acs-image-sbom/1.0/acs-image-sbom.yaml
        resolver: git
      runAfter:
        - acs-check-image
      params:
        - name: image
          value: $(params.IMAGE_DEST_URL)@$(tasks.build.results.IMAGE_DIGEST)
        - name: cyclonedxHostUrl
          value: https://server.apps.hub.ocplab.com
      when:
        - input: "$(workspaces.acs-central.bound)"
          operator: in
          values: ["true"]
      workspaces:
        - name: acs-central
          workspace: acs-central
        - name: upload-sbom
          workspace: upload-sbom
  workspaces:
    - name: git-source
    - name: acs-central
      optional: true
    - name: upload-sbom
      optional: true
