apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-deployments-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: petclinic
  target:
    name: slack-deployments-webhook
  data:
    - secretKey: url
      remoteRef:
        key: SLACK_DEPLOYMENTS
