---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: petclinic-webhook
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
        labels:
          tekton.dev/pipeline: petclinic
        generateName: petclinic-webhook-
      spec:
        pipelineRef:
          name: petclinic
        timeouts:
          pipeline: 1h0m0s
      workspaces:
        - name: git-source
          persistentVolumeClaim:
            claimName: source
        - name: m2-cache
          persistentVolumeClaim:
            claimName: m2-cache
        - name: acs-central
          secret:
            secretName: acs-central
        - name: upload-sbom
          secret:
            secretName: upload-sbom
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: petclinic
spec:
  serviceAccountName: pipeline
  triggers:
    - name: petclinic-webhook
      template:
        ref: petclinic-webhook
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: petclinic
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: petclinic
    eventlistener: petclinic
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-petclinic
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
