extends: default

ignore:
  - /clusters/templates/cluster-config-appset.yaml

rules:
  comments-indentation: disable
  document-start: disable
  indentation:
    indent-sequences: whatever
  line-length: disable
  truthy:
    ignore: .github/workflows/
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
