apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: petclinic
spec:
  key: argocd-health-petclinic
  promotionStrategyRef:
    name: petclinic
  applicationSelector:
    matchLabels:
      app: petclinic
  url:
    template: https://argocd-server-argocd.apps.hub.ocplab.com/applications/petclinic-argocd/petclinic-{{ .Environment | base }}
