apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-argocd

resources:
  - ../../base
  - acs-commit-status.yaml
  - argocd-commit-status.yaml
  - github-checks-commit-status.yaml
  - promotion-strategy.yaml
