FROM registry.access.redhat.com/ubi10-minimal
ARG USER_HOME_DIR="/home/default"
ARG WORK_DIR="/home/default"
ARG M2_HOME_DIR="/home/default/.m2"

ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot

COPY --chown=0:0 entrypoint.sh /

USER 0

RUN microdnf --disableplugin=subscription-manager install -y openssl git tar shadow-utils bash podman aardvark-dns fuse-overlayfs util-linux maven maven-openjdk21 java-21-openjdk-devel ; \
    microdnf update -y ; \
    microdnf clean all ; \
    chmod +x /entrypoint.sh ; \
    ##
    ## Setup for root-less podman
    ##
    # Create the User's home directory
    mkdir -p ${USER_HOME_DIR} ; \
    chown -R 1000:1000 ${USER_HOME_DIR} ; \
    #
    # Create the M2 home directory to support M2 caching in Tekton
    mkdir -p ${M2_HOME_DIR} ; \
    chown -R 1000:1000 ${M2_HOME_DIR} ; \

    # Add the user to /etc/passwd and /etc/group
    echo "user:x:1000:1000:default user:${USER_HOME_DIR}:/bin/bash" >> /etc/passwd ; \
    echo "user:x:1000:" >> /etc/group ; \
    #
    # Add entries for uid and gid mappings for the user
    echo "user:1001:64535" >> /etc/subuid ; \
    echo "user:1001:64535" >> /etc/subgid ; \
    #
    # Enable podman to create uid and gid maps for the user
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ; \
    #
    # Setup podman socket for podman service started in entrypoint.sh
    mkdir -p /run/podman; \
    chown 1000 /run/podman

# The SCC that we are using will ensure that the user runs as UID 1000 in its own user namespace on the host node.
USER 1000

ENV DOCKER_HOST=unix:///run/podman/podman.sock

ENV TESTCONTAINERS_RYUK_DISABLED=true
ENV TESTCONTAINERS_REUSE_ENABLE=false

WORKDIR ${WORK_DIR}
# Using catatonit ensures that our running container has a process reaper.  This avoids zombie processes in the container.
#ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
# Don't use catatonit with tekton because we don't want our podman service reaped and the container is short lived so the process is cleaned up by cgroups
ENTRYPOINT ["/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
