apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-ci

resources:
#- scc-binding.yaml
- docker-external-secret.yaml
- m2-cache-pvc.yaml
- source-pvc.yaml
- maven-task.yaml
- pipeline-sa.yaml
- pipeline.yaml
