apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: acs-policy-violation
spec:
  promotionStrategyRef:
    name: petclinic
  key: acs-policy-violation
  reportOn: active
  descriptionTemplate: 'status: {{ index .SuccessVariables "status" }}, critical: {{ index .SuccessVariables "critical" }}, high: {{ index .SuccessVariables "high" }} '
  httpRequest:
    urlTemplate: https://central-rhacs-operator.apps.hub.ocplab.com/v1/alerts?query=Namespace:petclinic-{{ .Branch | splitList "/" | last }}
    methodTemplate: GET
    timeout: 30s
    authentication:
      bearer:
        secretRef:
          name: acs-api-token
  success:
    when:
      variables:
        expression: |
          let default = {
            status: "Pending",
            critical: 0,
            high: 0,
            medium: 0,
            low: 0,
          };
          Response != nil ?
            Response.StatusCode == 200 ?
              {
                critical: count(Response.Body.alerts, .policy.severity=="CRITICAL_SEVERITY"),
                high: count(Response.Body.alerts, .policy.severity=="HIGH_SEVERITY"),
                medium: count(Response.Body.alerts, .policy.severity=="MEDIUM_SEVERITY"),
                low: count(Response.Body.alerts, .policy.severity=="LOW_SEVERITY"),
                total: len(Response.Body.alerts),
                status: "Success"
              } :
              {
                status: "Failed (" + Response.StatusCode + ")",
                critical: 0,
                high: 0,
                medium: 0,
                low: 0,
              }
           : default
      expression: |
        Variables.status == "Success" && Variables.critical == 0
      output:
        expression: 'Variables'
  mode:
    context: promotionstrategy
    polling:
      interval: 1m
