apiVersion: promoter.argoproj.io/v1alpha1
kind: WebRequestCommitStatus
metadata:
  name: acs-policy-violation
spec:
  promotionStrategyRef:
    name: petclinic
  key: acs-policy-violation
  reportOn: active
  descriptionTemplate: 'Validating ACS Policies ({{ .Phase }}) for {{ index .TriggerVariables "currentSha" }}'
  httpRequest:
    urlTemplate: https://central-rhacs-operator.apps.hub.ocplab.com/v1/alerts?query=Namespace:petclinic-{{ .Branch | splitList "/" | last }}&State:ACTIVE
    methodTemplate: GET
    timeout: 30s
    authentication:
      bearer:
        secretRef:
          name: acs-api-token
  success:
    when:
      variables:
        expression: |
          Response != nil ? {
            critical: count(Response.Body.alerts, .policy.severity=="CRITICAL_SEVERITY"),
            high: count(Response.Body.alerts, .policy.severity=="HIGH_SEVERITY"),
            medium: count(Response.Body.alerts, .policy.severity=="MEDIUM_SEVERITY"),
            low: count(Response.Body.alerts, .policy.severity=="LOW_SEVERITY"),
            total: len(Response.Body.alerts),
            success: Response.StatusCode == 200
          } :
          {
            success: false
          }
      expression: "Variables.success"
      response:
        output:
          expression: 'Variables'
  mode:
    context: promotionstrategy
    polling:
      interval: 5m
