apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-argocd

resources:
  - acs-token-secret.yaml
  - image-updater-role.yaml
  - github-external-secret.yaml
  - gitops-promoter-github-app-key.yaml
  - scm-provider.yaml
  - git-repository.yaml
  - image-updater.yaml
