apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: petclinic
spec:
  activeCommitStatuses:
    - key: argocd-health-petclinic
    - key: acs-policy-violation
  environments:
    - autoMerge: true
      branch: environment/dev
    - autoMerge: true
      branch: environment/stage
      activeCommitStatuses:
        - key: argocd-health-petclinic
        - key: acs-policy-violation
    - autoMerge: true
      branch: environment/prod
      activeCommitStatuses:
        - key: argocd-health-petclinic
        - key: acs-policy-violation
  gitRepositoryRef:
    name: petclinic
