apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: petclinic
spec:
  activeCommitStatuses:
    - key: argocd-health-petclinic
    - key: acs-policy-violation
  environments:
    - autoMerge: true
      branch: environment/dev
      proposedCommitStatuses:
        - key: github-required-checks
    - autoMerge: true
      branch: environment/stage
      proposedCommitStatuses:
        - key: github-required-checks
    - autoMerge: true
      branch: environment/prod
      proposedCommitStatuses:
        - key: github-required-checks
  gitRepositoryRef:
    name: petclinic
