apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app: petclinic
      app.kubernetes.io/component: petclinic
      app.kubernetes.io/instance: petclinic
      app.kubernetes.io/name: petclinic
      app.kubernetes.io/part-of: petclinic
      app.openshift.io/runtime-icon: quarkus
resources:
  - monitor-auth-secret.yaml
  - petclinic-svc.yaml
  - petclinic-route.yaml
  - petclinic-rollout.yaml
  - smoke-test-analysis.yaml
images:
  - name: quay.io/gnunn/quarkus-petclinic
    newName: quay.io/gnunn/quarkus-petclinic
    newTag: a2bdaba-3HbNuFoWb6lQ47z05PrzU1BWqRI
