apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
  name: monitor-auth-secret
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitor-auth-secret
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["monitor-auth-secret"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-auth-secret
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: rollout-manager
roleRef:
  kind: Role
  name: monitor-auth-secret
  apiGroup: rbac.authorization.k8s.io
