apiVersion: v1
kind: Service
metadata:
  name: petclinic-stable
spec:
  ports:
  - name: 8080-tcp
    port: 8080
  - name: 8443-tcp
    port: 8443
  selector:
    app: petclinic
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-canary
spec:
  ports:
  - name: 8080-tcp
    port: 8080
  - name: 8443-tcp
    port: 8443
  selector:
    app: petclinic
