#!/bin/bash
# shellcheck disable=SC2034,SC2044

# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$(pwd)"

function display_help {
  echo "./$(basename "$0") [ -d | --directory DIRECTORY ] [ -q | --quiet ] [ -h | --help | --vpc-keypair | --lab | --teardown | --redeploy | --clear-logs ] [ OPTIONAL ANSIBLE OPTIONS ]
Script to validate the manifests generated by Kustomize
Where:
  -d  | --directory DIRECTORY  Base directory containing Kustomize overlays
  -e  | --enforce-all-schemas  Enable enforcement of all schemas
  -h  | --help                 Display this help text
  -sl | --schema-location      Location containing schemas"
}

KUBERNETES_VERSION="1.34.5"
IGNORE_MISSING_SCHEMAS="-ignore-missing-schemas"
SCHEMA_LOCATION="${DIR}/openshift-json-schema"
KUSTOMIZE_DIRS="${DIR}"
ERROR_COLOR='\033[0;31m'
NO_COLOR='\033[0m'
POLICY_GENERATOR_VERSION="v1.17.1"
POLICY_GENERATOR_PATH="${HOME}/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator"
export POLICY_GEN_ENABLE_HELM=true

# Install the Policy Generator kustomize plugin
echo "Installing PolicyGenerator ${POLICY_GENERATOR_VERSION} at ${POLICY_GENERATOR_PATH}"

mkdir -p ${POLICY_GENERATOR_PATH}
curl -sSL https://github.com/open-cluster-management-io/policy-generator-plugin/releases/download/${POLICY_GENERATOR_VERSION}/linux-amd64-PolicyGenerator -o ${POLICY_GENERATOR_PATH}/PolicyGenerator
chmod +x ${POLICY_GENERATOR_PATH}/PolicyGenerator

for i in "$@"
do
  case $i in
    -d=* | --directory=* )
      KUSTOMIZE_DIRS="${i#*=}"
      shift
      ;;
    -e | --enforce-all-schemas )
      shift
      IGNORE_MISSING_SCHEMAS=""
      shift
      ;;
    -sl=* | --schema-location=* )
      SCHEMA_LOCATION="${i#*=}"
      shift
      ;;
    -h | --help )
      display_help
      exit 0
      ;;
  esac
done

errors=0

# Validate kustomize
for i in $(find "${KUSTOMIZE_DIRS}" -name "kustomization.yaml" -exec dirname {} \;)
do
  echo
  echo "Validating $i"
  echo

  if [ -f "$i/.skip_validation" ]; then
    echo "Skipping validation due to .skip_validation marker file"
    continue
  fi

  if grep -q "kind: Component" "$i/kustomization.yaml"; then
    echo "Kustomize component, skipping validation"
    continue
  fi

  KUSTOMIZE_BUILD_OUTPUT=$(kustomize build --enable-helm --enable-alpha-plugins "$i")

  build_response=$?

  if [ $build_response -ne 0 ]; then
    >&2 echo -e "${ERROR_COLOR}Error building $i${NO_COLOR}"
    errors=$((errors + 1))
  fi

 # Validate with kubeconform but ignore missing schemas
 echo "$KUSTOMIZE_BUILD_OUTPUT" | kubeconform $IGNORE_MISSING_SCHEMAS -kubernetes-version $KUBERNETES_VERSION \
   -schema-location 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{ .NormalizedKubernetesVersion }}-standalone{{ .StrictSuffix }}/{{ .ResourceKind }}{{ .KindSuffix }}.json' \
   -schema-location 'https://raw.githubusercontent.com/melmorabity/openshift-json-schemas/main/v4.20-standalone{{ .StrictSuffix }}/{{ .ResourceKind }}{{ .KindSuffix }}.json' \
   -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'

 validation_response=$?

 if [ $validation_response -ne 0 ]; then
   echo "Warning validating $i"
 fi
done

# Validate helm
for i in $(find "${KUSTOMIZE_DIRS}" -name "Chart.yaml" -exec dirname {} \;)
do

  echo
  echo "Validating $i"
  echo

  if [ -f "$i/.skip_validation" ]; then
    echo "Skipping validation due to .skip_validation marker file"
    continue
  fi

  HELM_BUILD_OUTPUT=$(helm template "$i")

  build_response=$?

  if [ $build_response -ne 0 ]; then
    >&2 echo -e "${ERROR_COLOR}Error building $i${NO_COLOR}"
    errors=$((errors + 1))
  fi

 # Validate with kubeconform but ignore missing schemas
 echo "$HELM_BUILD_OUTPUT" | kubeconform $IGNORE_MISSING_SCHEMAS -kubernetes-version $KUBERNETES_VERSION \
   -schema-location 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{ .NormalizedKubernetesVersion }}-standalone{{ .StrictSuffix }}/{{ .ResourceKind }}{{ .KindSuffix }}.json' \
   -schema-location 'https://raw.githubusercontent.com/melmorabity/openshift-json-schemas/main/v4.20-standalone{{ .StrictSuffix }}/{{ .ResourceKind }}{{ .KindSuffix }}.json' \
   -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' || true

 validation_response=$?

 if [ $validation_response -ne 0 ]; then
   echo "Warning validating $i"
 fi

done

echo
if [ $errors -ne 0 ]; then
  echo -e "${ERROR_COLOR}$errors Errors occurred, see logs${NO_COLOR}"
  exit 1
else
  echo "Manifests successfully validated!"
fi
