name: Hydrate Dev Manifests
on:
  push:
    branches:
      - "main"
    paths:
      - "apps/petclinic/**"
      - "apps/petclinic-db/**"
      - "environments/**/**"

jobs:
  hydrate-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GITOPS_ACTION_TOKEN_ID }}
          private-key: ${{ secrets.GITOPS_ACTION_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "gnunn-gitops-app"
          git config --global user.email "gnunn-gitops-app@users.noreply.github.com"
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Create and push dev-next branch
        run: |
          ./scripts/hydrate.sh dev
        with:
          token: ${{ steps.app-token.outputs.token }}

  hydrate-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GITOPS_ACTION_TOKEN_ID }}
          private-key: ${{ secrets.GITOPS_ACTION_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "gnunn-gitops-app"
          git config --global user.email "gnunn-gitops-app@users.noreply.github.com"
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Create and push stage-next branch
        run: |
          ./scripts/hydrate.sh stage
        with:
          token: ${{ steps.app-token.outputs.token }}

  hydrate-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GITOPS_ACTION_TOKEN_ID }}
          private-key: ${{ secrets.GITOPS_ACTION_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "gnunn-gitops-app"
          git config --global user.email "gnunn-gitops-app@users.noreply.github.com"
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Create and push stage-next branch
        run: |
          ./scripts/hydrate.sh prod
        with:
          token: ${{ steps.app-token.outputs.token }}
