name: Hydrate Manifests
on:
  push:
    branches:
      - "*"

jobs:
  hydrate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create and push development-next branch
        run: |
          export ENV=dev
          ./scripts/hydrate.sh
