name: Hydrate Dev Manifests
on:
  push:
    branches:
      - "main"
    paths:
      - "apps/petclinic/**"
      - "apps/petclinic-db/**"
      - "environments/**/**"

jobs:
  hydrate-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GITOPS_ACTION_TOKEN_ID }}
          private-key: ${{ secrets.GITOPS_ACTION_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        with:
          token: ${{ slots.generate-token.outputs.token }}
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ slots.generate-token.outputs.token }}
      - name: Create and push dev-next branch
        run: |
          ./scripts/hydrate.sh dev

  hydrate-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GITOPS_ACTION_TOKEN_ID }}
          private-key: ${{ secrets.GITOPS_ACTION_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        with:
          token: ${{ slots.generate-token.outputs.token }}
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ slots.generate-token.outputs.token }}
      - name: Create and push stage-next branch
        run: |
          ./scripts/hydrate.sh stage

  hydrate-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GITOPS_ACTION_TOKEN_ID }}
          private-key: ${{ secrets.GITOPS_ACTION_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        with:
          token: ${{ slots.generate-token.outputs.token }}
      - name: Code Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ slots.generate-token.outputs.token }}
      - name: Create and push stage-next branch
        run: |
          ./scripts/hydrate.sh prod
