name: Validate Image
on:
  pull_request:
    branches:
      - "environment/prod"
      - "environment/stage"
      - "environment/dev"
      - "main"

  push:
    branches:
      - "main"
      # - "environment/*-next"

jobs:
  validate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
      - name: Get Image
        id: get-image
        run: |
          export PETCLINIC_IMAGE_URL=$(kustomize build apps/petclinic/base | yq '. | select(.kind == "Rollout" and .metadata.name == "petclinic") | .spec.template.spec.containers[].image' | tr -d '"')
          PETCLINIC_TAG=$(echo -n "${PETCLINIC_IMAGE_URL##*:}")
          echo "Testing image: $PETCLINIC_IMAGE_URL"
          echo "Testing tag: $PETCLINIC_TAG"
          echo -n "petclinic_tag=$PETCLINIC_TAG" >> $GITHUB_OUTPUT
      - name: Run EC Validator
        uses: conforma/action-validate-image@v1.0.421
        with:
          image: quay.io/gnunn/quarkus-petclinic:${{ steps.get-image.outputs.petclinic_tag }}
          policy: github.com/conforma/config//slsa3
          extra-params: --ignore-rekor
          identity: tekton-builder@rhdp.com
          issuer: https://sso.ocplab.com/realms/ocplab
